"""ORM model registry — importing this package registers every table."""

from __future__ import annotations

from app.models.academics import (
    ATTENDANCE_STATUSES,
    CLASS_LEVELS,
    FEE_STATUSES,
    CommunicationLog,
    DailySubmissionLog,
    ExamSubmissionEvent,
    LiveAttendance,
    SchoolClass,
    Student,
    StudentGrade,
    Subject,
    TeachingAssignment,
)
from app.models.base import Base
from app.models.finance import (
    PAYMENT_STATUSES,
    PaymentTransaction,
    SecurityAuditLog,
    StudentInvoice,
    TuitionRate,
)
from app.models.identity import AcademicYear, PrivateSchool, SchoolRollSequence, User
from app.models.operations import (
    ABSENCE_STATUSES,
    BIOMETRIC_METHODS,
    BIOMETRIC_OWNER_TYPES,
    BACKUP_KINDS,
    BackupAuditEvent,
    BackupRecord,
    BiometricCredential,
    BiometricVerificationLog,
    CREDENTIAL_STATUSES,
    DataChangeLog,
    SUBSTITUTION_STATUSES,
    SYLLABUS_STATUSES,
    SubstitutionAssignment,
    SyllabusPlan,
    SyllabusProgressEntry,
    TeacherAbsence,
    TIMETABLE_PERIODS,
    TimetableSlot,
    VERIFICATION_PURPOSES,
    VERIFICATION_RESULTS,
    VerificationResult,
)

__all__ = [
    "Base",
    "ATTENDANCE_STATUSES",
    "ABSENCE_STATUSES",
    "BACKUP_KINDS",
    "BIOMETRIC_METHODS",
    "BIOMETRIC_OWNER_TYPES",
    "CLASS_LEVELS",
    "CREDENTIAL_STATUSES",
    "FEE_STATUSES",
    "PAYMENT_STATUSES",
    "SUBSTITUTION_STATUSES",
    "SYLLABUS_STATUSES",
    "TIMETABLE_PERIODS",
    "AcademicYear",
    "BackupAuditEvent",
    "BackupRecord",
    "BiometricCredential",
    "BiometricVerificationLog",
    "CommunicationLog",
    "DailySubmissionLog",
    "DataChangeLog",
    "ExamSubmissionEvent",
    "LiveAttendance",
    "PaymentTransaction",
    "PrivateSchool",
    "SchoolClass",
    "SchoolRollSequence",
    "SecurityAuditLog",
    "Student",
    "StudentGrade",
    "StudentInvoice",
    "Subject",
    "SubstitutionAssignment",
    "SyllabusPlan",
    "SyllabusProgressEntry",
    "TeacherAbsence",
    "TeachingAssignment",
    "TimetableSlot",
    "TuitionRate",
    "User",
    "VERIFICATION_PURPOSES",
    "VERIFICATION_RESULTS",
    "VerificationResult",
]
