-- ============================================================================
-- NE-EMIS — National Education Management Information System
-- PostgreSQL 15+ schema
--
-- Design goals
--   * Multi-tenant (campus-isolated) read/write with centralized state
--     aggregation.
--   * Persistent global identifiers:
--       NE-SID  -> students.id / students.ne_sid
--       NE-TID  -> teachers.id / teachers.ne_tid
--       NE-MID  -> managers.id / managers.ne_mid
--       NE-CID  -> course_sections.id / course_sections.ne_cid
--   * Campus-level Row-Level Security (RLS) so campus clerks/deans only see
--     and write their own campus; the state role reads the global registry.
--   * Cryptographic record locking: dean Ed25519 signatures are stored in
--     record_locks and database triggers freeze the payload rows.
--   * Immutable core identifiers: every identifier column is generated by a
--     BEFORE INSERT trigger and is never updated.
--
-- Execute as a superuser / owner:
--   psql -v ON_ERROR_STOP=1 -f sql/001_schema.sql
-- ============================================================================

BEGIN;

-- gen_random_uuid() is built into PostgreSQL 13+; citext is the only
-- contributed extension the schema requires. Keep it minimal so the schema
-- runs on the official postgres image without extra contrib packages.
CREATE EXTENSION IF NOT EXISTS citext;     -- case-insensitive codes

-- ---------------------------------------------------------------------------
-- ENUMs
-- ---------------------------------------------------------------------------
CREATE TYPE campus_type       AS ENUM ('pre_primary','primary','secondary','tvet','tertiary','adult_ed');
CREATE TYPE gender            AS ENUM ('male','female','other');
CREATE TYPE person_status     AS ENUM ('active','suspended','withdrawn','transferred','graduated','expired','deceased');
CREATE TYPE enrollment_kind   AS ENUM ('k12','tvet','higher_education','adult');
CREATE TYPE term_type         AS ENUM ('first','second','third','semester_a','semester_b','summer','full_year');
CREATE TYPE transfer_state    AS ENUM ('none','drafted','in_progress','approved','cleared','rejected');
CREATE TYPE mobility_edge     AS ENUM ('promotion','horizontal_transfer','upgrade','downgrade','re-entry');
CREATE TYPE employment_state  AS ENUM ('active','on_leave','suspended','transferred','retired','terminated');
CREATE TYPE degree_level      AS ENUM ('certificate','diploma','bachelors','masters','doctorate','other');
CREATE TYPE cert_state        AS ENUM ('pending','active','suspended','revoked','expired');
CREATE TYPE cert_kind         AS ENUM ('teaching_license','police_clearance','safety_certificate','special_education','other');
CREATE TYPE attendance_status AS ENUM ('present','absent','late','excused','truant');
CREATE TYPE incident_kind     AS ENUM ('academic','behavioral','safety','bullying','substance','other');
CREATE TYPE incident_level    AS ENUM ('low','medium','high','critical');
CREATE TYPE grade_band        AS ENUM ('A','B','C','D','E','F','NG');
CREATE TYPE course_role       AS ENUM ('lead','co_teacher','support','invigilator');
CREATE TYPE lock_state        AS ENUM ('unlocked','locked');
CREATE TYPE batch_state       AS ENUM ('queued','running','completed','failed','cancelled');
CREATE TYPE payout_state      AS ENUM ('pending','approved','paid','failed','void','reversed');
CREATE TYPE funding_kind      AS ENUM ('capitation','teacher_payroll','hardship_allowance','infrastructure','program_based','emergency');
CREATE TYPE signature_scheme  AS ENUM ('ed25519','rs256','es256');
CREATE TYPE data_source       AS ENUM ('portal','mobile','api','batch','legacy');
CREATE TYPE lock_entity       AS ENUM ('attendance','exam_sheet','grade','payroll_entry','teacher_profile','classroom','course_section','student_record');

-- ---------------------------------------------------------------------------
-- RLS / tenancy helper functions
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS central;

CREATE OR REPLACE FUNCTION app.current_campus_id() RETURNS uuid AS $$
  SELECT NULLIF(current_setting('neemis.campus_id', true), '')::uuid;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION app.current_role() RETURNS text AS $$
  SELECT COALESCE(NULLIF(current_setting('neemis.role', true), ''), 'anonymous');
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION app.is_state_role() RETURNS boolean AS $$
  SELECT app.current_role() IN ('state_admin', 'system', 'aggregator');
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION app.assert_campus_match() RETURNS trigger AS $$
BEGIN
  IF NEW.campus_id IS DISTINCT FROM app.current_campus_id()
     AND NOT app.is_state_role() THEN
    RAISE EXCEPTION 'neemis.campus_mismatch: row campus_id % does not match session %',
      NEW.campus_id, app.current_campus_id();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger body manually added to tenant tables that need campus assertion.

-- Immutable public identifier generators -----------------------------------
CREATE OR REPLACE FUNCTION app.gen_ne_sid() RETURNS trigger AS $$
BEGIN
  IF NEW.id IS NULL THEN NEW.id := gen_random_uuid(); END IF;
  NEW.ne_sid := 'NE-SID-' || replace(new.id::text, '-', '');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION app.gen_ne_tid() RETURNS trigger AS $$
BEGIN
  IF NEW.id IS NULL THEN NEW.id := gen_random_uuid(); END IF;
  NEW.ne_tid := 'NE-TID-' || replace(new.id::text, '-', '');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION app.gen_ne_mid() RETURNS trigger AS $$
BEGIN
  IF NEW.id IS NULL THEN NEW.id := gen_random_uuid(); END IF;
  NEW.ne_mid := 'NE-MID-' || replace(new.id::text, '-', '');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION app.gen_ne_cid() RETURNS trigger AS $$
BEGIN
  IF NEW.id IS NULL THEN NEW.id := gen_random_uuid(); END IF;
  NEW.ne_cid := 'NE-CID-' || upper(new.state_code) || '-' || upper(new.section_code) || '-' || replace(new.id::text, '-', '');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- 1. CAMPUS TENANT
-- ---------------------------------------------------------------------------
CREATE TABLE public.campus (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_code     citext UNIQUE NOT NULL,
    campus_type     campus_type NOT NULL,
    name            text NOT NULL,
    state_code      char(2)  NOT NULL,
    region          text NOT NULL,
    lga             text,
    postal_address  text,
    geo_lat         numeric(10,7),
    geo_lng         numeric(10,7),
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_campus_coords CHECK (
        (geo_lat IS NULL OR geo_lat BETWEEN -90 AND 90) AND
        (geo_lng IS NULL OR geo_lng BETWEEN -180 AND 180)
    )
);

-- ---------------------------------------------------------------------------
-- 2. IDENTITY & ACCESS (globally keyed managers / users)
-- ---------------------------------------------------------------------------
CREATE TABLE public.app_users (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    username        citext UNIQUE NOT NULL,
    email           citext UNIQUE,
    role            text NOT NULL CHECK (role IN ('clerk','dean','state_admin','system','aggregator')),
    campus_id       uuid REFERENCES public.campus(id),
    password_hash   text NOT NULL,
    is_active       boolean NOT NULL DEFAULT true,
    last_login_at   timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- NE-MID: global manager identity. Cryptographic verification keys live here.
CREATE TABLE public.managers (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ne_mid                  text UNIQUE NOT NULL,
    user_id                 uuid NOT NULL UNIQUE REFERENCES public.app_users(id),
    campus_id               uuid NOT NULL REFERENCES public.campus(id),
    full_name               text NOT NULL,
    designation             text NOT NULL,          -- principal, dean, bursar, state_director ...
    is_account_holder       boolean NOT NULL DEFAULT false,
    verification_public_key bytea,                  -- Ed25519 SPKI
    signature_scheme        signature_scheme NOT NULL DEFAULT 'ed25519',
    key_version             int NOT NULL DEFAULT 1,
    key_activated_at        timestamptz,
    key_revoked_at          timestamptz,
    is_active               boolean NOT NULL DEFAULT true,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_managers_gen_mid BEFORE INSERT ON public.managers
  FOR EACH ROW EXECUTE FUNCTION app.gen_ne_mid();

-- ---------------------------------------------------------------------------
-- 3. STUDENTS & MOBILITY MATRIX
-- ---------------------------------------------------------------------------
CREATE TABLE public.students (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ne_sid              text UNIQUE NOT NULL,
    campus_id           uuid NOT NULL REFERENCES public.campus(id),
    national_id_hash    text,                       -- salted SHA-256, never plaintext
    first_name          text NOT NULL,
    middle_name         text,
    last_name           text NOT NULL,
    dob                 date NOT NULL,
    gender              gender NOT NULL,
    coordinates         point,
    enrollment_kind     enrollment_kind NOT NULL DEFAULT 'k12',
    current_major       text,                       -- FK-level via majors
    current_grade_level text,
    status              person_status NOT NULL DEFAULT 'active',
    guardian_name       text,
    guardian_phone      text,
    matriculated_on     date NOT NULL DEFAULT CURRENT_DATE,
    is_dual_enrollment_suspect boolean NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_student_dob CHECK (dob < CURRENT_DATE)
);
CREATE TRIGGER trg_students_gen_sid BEFORE INSERT ON public.students
  FOR EACH ROW EXECUTE FUNCTION app.gen_ne_sid();
CREATE TRIGGER trg_students_campus_match BEFORE INSERT OR UPDATE ON public.students
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();

CREATE TABLE public.majors (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_id     uuid NOT NULL REFERENCES public.campus(id),
    code          citext NOT NULL,
    title         text NOT NULL,
    faculty       text,
    is_active     boolean NOT NULL DEFAULT true,
    UNIQUE (campus_id, code)
);

CREATE TABLE public.academic_years (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    label         citext UNIQUE NOT NULL,   -- 2025/2026
    starts_on     date NOT NULL,
    ends_on       date NOT NULL
);

CREATE TABLE public.terms (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    academic_year_id  uuid NOT NULL REFERENCES public.academic_years(id),
    term_type         term_type NOT NULL,
    starts_on         date NOT NULL,
    ends_on           date NOT NULL,
    UNIQUE (academic_year_id, term_type)
);

CREATE TABLE public.enrollments (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id         uuid NOT NULL REFERENCES public.students(id),
    campus_id          uuid NOT NULL REFERENCES public.campus(id),
    academic_year_id   uuid NOT NULL REFERENCES public.academic_years(id),
    term_id            uuid REFERENCES public.terms(id),
    major_id           uuid REFERENCES public.majors(id),
    grade_level        text,
    section_name       text,
    status             person_status NOT NULL DEFAULT 'active',
    matriculated_on    date NOT NULL DEFAULT CURRENT_DATE,
    created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_enrollments_campus_match BEFORE INSERT OR UPDATE ON public.enrollments
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();

-- Chronological schooling-history tree (authoritative provenance chain).
-- `previous_mobility_id` models the tree and prevents double-enrollment.
CREATE TABLE public.student_mobility (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id           uuid NOT NULL REFERENCES public.students(id),
    campus_id            uuid NOT NULL REFERENCES public.campus(id),   -- acting campus
    from_campus_id       uuid REFERENCES public.campus(id),
    to_campus_id         uuid NOT NULL REFERENCES public.campus(id),
    from_enrollment_id   uuid REFERENCES public.enrollments(id),
    to_enrollment_id     uuid REFERENCES public.enrollments(id),
    previous_mobility_id uuid REFERENCES public.student_mobility(id),
    edge_type            mobility_edge NOT NULL DEFAULT 'horizontal_transfer',
    transfer_state       transfer_state NOT NULL DEFAULT 'drafted',
    requested_on         date NOT NULL DEFAULT CURRENT_DATE,
    effective_on         date,
    notes                text,
    signed_manifest      bytea,                  -- dean-signed transfer clearance junction
    created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.transfer_clearances (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    mobility_id      uuid NOT NULL REFERENCES public.student_mobility(id),
    campus_id        uuid NOT NULL REFERENCES public.campus(id),
    clearance_type   text NOT NULL CHECK (clearance_type IN ('academic','financial','disciplinary','hostel','library')),
    issued_by        uuid NOT NULL REFERENCES public.managers(id),
    clearance_state  text NOT NULL CHECK (clearance_state IN ('pending','issued','void')),
    signed_document  bytea NOT NULL,
    issued_at        timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 4. COURSES / TEACHER LOAD (NE-CID composite binding)
-- ---------------------------------------------------------------------------
CREATE TABLE public.state_curricula (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    state_code         char(2) NOT NULL,
    subject_code       citext NOT NULL,
    subject_name       text NOT NULL,
    curriculum_version int NOT NULL DEFAULT 1,
    is_active          boolean NOT NULL DEFAULT true,
    UNIQUE (state_code, subject_code, curriculum_version)
);

CREATE TABLE public.classrooms (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_id    uuid NOT NULL REFERENCES public.campus(id),
    room_code    citext NOT NULL,
    building     text,
    capacity     int NOT NULL DEFAULT 40,
    is_laboratory boolean NOT NULL DEFAULT false,
    is_active    boolean NOT NULL DEFAULT true,
    UNIQUE (campus_id, room_code),
    CONSTRAINT chk_capacity CHECK (capacity > 0)
);
CREATE TRIGGER trg_classrooms_campus_match BEFORE INSERT OR UPDATE ON public.classrooms
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();

CREATE TABLE public.course_sections (
    id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ne_cid                text UNIQUE NOT NULL,
    campus_id             uuid NOT NULL REFERENCES public.campus(id),
    state_code            char(2) NOT NULL,
    curriculum_id         uuid NOT NULL REFERENCES public.state_curricula(id),
    academic_year_id      uuid NOT NULL REFERENCES public.academic_years(id),
    term_id               uuid NOT NULL REFERENCES public.terms(id),
    classroom_id          uuid NOT NULL REFERENCES public.classrooms(id),
    teacher_id            uuid,                    -- filled once assigned
    section_code          citext NOT NULL,
    enrolled_count        int NOT NULL DEFAULT 0,
    weekly_contact_hours  numeric(5,1) NOT NULL DEFAULT 0,
    schedule_json         jsonb NOT NULL DEFAULT '[]'::jsonb,
    is_active             boolean NOT NULL DEFAULT true,
    created_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (campus_id, curriculum_id, academic_year_id, term_id, section_code)
);
CREATE TRIGGER trg_sections_campus_match BEFORE INSERT OR UPDATE ON public.course_sections
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();
CREATE TRIGGER trg_sections_gen_cid BEFORE INSERT ON public.course_sections
  FOR EACH ROW EXECUTE FUNCTION app.gen_ne_cid();

CREATE TABLE public.course_enrollments (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id        uuid NOT NULL REFERENCES public.students(id),
    course_section_id uuid NOT NULL REFERENCES public.course_sections(id),
    campus_id         uuid NOT NULL REFERENCES public.campus(id),
    status            person_status NOT NULL DEFAULT 'active',
    enrolled_on       date NOT NULL DEFAULT CURRENT_DATE,
    UNIQUE (student_id, course_section_id)
);
CREATE TRIGGER trg_course_enrollments_campus_match BEFORE INSERT OR UPDATE ON public.course_enrollments
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();

-- ---------------------------------------------------------------------------
-- 5. ACADEMIC ARTIFACTS (transcripts, grades, exams, attendance, behaviour)
-- ---------------------------------------------------------------------------
CREATE TABLE public.transcripts (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id         uuid NOT NULL REFERENCES public.students(id),
    campus_id          uuid NOT NULL REFERENCES public.campus(id),
    academic_year_id   uuid NOT NULL REFERENCES public.academic_years(id),
    term_id            uuid REFERENCES public.terms(id),
    cumulative_gpa     numeric(4,2) NOT NULL DEFAULT 0,
    credits_earned     numeric(6,1) NOT NULL DEFAULT 0,
    class_rank         int,
    is_inherited       boolean NOT NULL DEFAULT false,   -- becomes true on transfer
    source_sin         uuid REFERENCES public.transcripts(id),  -- source institution transcript
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.exam_sheets (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_section_id uuid NOT NULL REFERENCES public.course_sections(id),
    student_id        uuid NOT NULL REFERENCES public.students(id),
    campus_id         uuid NOT NULL REFERENCES public.campus(id),
    exam_type         text NOT NULL CHECK (exam_type IN ('continuous','midterm','final','mock')),
    score             numeric(5,2) NOT NULL CHECK (score BETWEEN 0 AND 100),
    grade_band        grade_band,
    recorded_by       uuid REFERENCES public.app_users(id),
    recorded_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_section_id, student_id, exam_type)
);

CREATE TABLE public.attendance (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id        uuid NOT NULL REFERENCES public.students(id),
    course_section_id uuid REFERENCES public.course_sections(id),
    campus_id         uuid NOT NULL REFERENCES public.campus(id),
    attendance_date   date NOT NULL DEFAULT CURRENT_DATE,
    status            attendance_status NOT NULL,
    hours             numeric(4,1) NOT NULL DEFAULT 0,
    clerk_id          uuid NOT NULL REFERENCES public.app_users(id),
    source            data_source NOT NULL DEFAULT 'portal',
    submitted_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (student_id, course_section_id, attendance_date),
    UNIQUE (student_id, attendance_date)
);
CREATE INDEX idx_attendance_campus_date ON public.attendance (campus_id, attendance_date);

CREATE TABLE public.incident_reports (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id    uuid NOT NULL REFERENCES public.students(id),
    campus_id     uuid NOT NULL REFERENCES public.campus(id),
    incident_date date NOT NULL DEFAULT CURRENT_DATE,
    kind          incident_kind NOT NULL,
    severity      incident_level NOT NULL DEFAULT 'low',
    description   text NOT NULL,
    reported_by   uuid NOT NULL REFERENCES public.app_users(id),
    resolved_by   uuid REFERENCES public.managers(id),
    resolved_at   timestamptz,
    status        person_status NOT NULL DEFAULT 'active'
);

CREATE TABLE public.truancy_marks (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id           uuid NOT NULL REFERENCES public.students(id),
    campus_id            uuid NOT NULL REFERENCES public.campus(id),
    academic_year_id     uuid NOT NULL REFERENCES public.academic_years(id),
    unexcused_absences   int NOT NULL DEFAULT 0,
    consecutive_misses   int NOT NULL DEFAULT 0,
    is_chronic           boolean NOT NULL DEFAULT false,
    last_recomputed_at   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 6. TEACHERS, QUALIFICATIONS, CERTIFICATIONS, PAYROLL GOVERNANCE
-- ---------------------------------------------------------------------------
CREATE TABLE public.teachers (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ne_tid          text UNIQUE NOT NULL,
    campus_id       uuid NOT NULL REFERENCES public.campus(id),
    user_id         uuid UNIQUE REFERENCES public.app_users(id),
    first_name      text NOT NULL,
    last_name       text NOT NULL,
    dob             date NOT NULL,
    national_id_hash text,
    employment_state employment_state NOT NULL DEFAULT 'active',
    hire_date       date NOT NULL DEFAULT CURRENT_DATE,
    exit_date       date,
    is_civil_service boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_teachers_gen_tid BEFORE INSERT ON public.teachers
  FOR EACH ROW EXECUTE FUNCTION app.gen_ne_tid();
CREATE TRIGGER trg_teachers_campus_match BEFORE INSERT OR UPDATE ON public.teachers
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();

-- NE-CID sections reference the lead teacher; added here because teachers is
-- defined after course_sections in this file.
ALTER TABLE public.course_sections
  ADD CONSTRAINT fk_course_sections_teacher
  FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);

CREATE TABLE public.teacher_qualifications (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id     uuid NOT NULL REFERENCES public.teachers(id),
    campus_id      uuid NOT NULL REFERENCES public.campus(id),
    degree_level   degree_level NOT NULL,
    field_of_study text NOT NULL,
    institution    text NOT NULL,
    awarded_year   int NOT NULL,
    certificate_no text,
    verification_doc bytea
);
CREATE TRIGGER trg_teacher_qualifications_campus_match BEFORE INSERT OR UPDATE ON public.teacher_qualifications
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();

CREATE TABLE public.teacher_certifications (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id   uuid NOT NULL REFERENCES public.teachers(id),
    campus_id    uuid NOT NULL REFERENCES public.campus(id),
    cert_kind    cert_kind NOT NULL,
    cert_no      text NOT NULL,
    issue_date   date NOT NULL,
    expiry_date  date,
    status       cert_state NOT NULL DEFAULT 'active',
    next_renewal date,
    document     bytea
);
CREATE INDEX idx_cert_expiry ON public.teacher_certifications (cert_kind, expiry_date) WHERE status = 'active';

CREATE TABLE public.teacher_assignments (
    id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id            uuid NOT NULL REFERENCES public.teachers(id),
    course_section_id     uuid NOT NULL REFERENCES public.course_sections(id),
    campus_id             uuid NOT NULL REFERENCES public.campus(id),
    role                  course_role NOT NULL DEFAULT 'lead',
    weekly_contact_hours  numeric(5,1) NOT NULL DEFAULT 0,
    lecture_space_id      uuid REFERENCES public.classrooms(id),
    UNIQUE (teacher_id, course_section_id)
);
CREATE TRIGGER trg_teacher_assignments_campus_match BEFORE INSERT OR UPDATE ON public.teacher_assignments
  FOR EACH ROW EXECUTE FUNCTION app.assert_campus_match();
CREATE INDEX idx_assignment_teacher ON public.teacher_assignments (teacher_id, campus_id);

-- Civil Service grade tiers -> base compensation + hardship multipliers.
CREATE TABLE public.civil_service_grades (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    grade_tier        int NOT NULL UNIQUE CHECK (grade_tier BETWEEN 1 AND 17),
    base_salary_naira numeric(14,2) NOT NULL CHECK (base_salary_naira > 0),
    hardship_multiplier numeric(4,2) NOT NULL DEFAULT 1.0,
    min_years_service int NOT NULL DEFAULT 0,
    is_active         boolean NOT NULL DEFAULT true
);

CREATE TABLE public.teacher_payroll_profiles (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id              uuid NOT NULL UNIQUE REFERENCES public.teachers(id),
    campus_id               uuid NOT NULL REFERENCES public.campus(id),
    grade_tier              int NOT NULL REFERENCES public.civil_service_grades(id),
    hardship_zone           text,
    regional_allowance      numeric(14,2) NOT NULL DEFAULT 0,
    bank_code               text,
    bank_account_encrypted  bytea,               -- AEAD-encrypted at rest
    bank_account_hash       text,
    tin                     text NOT NULL UNIQUE,
    pension_rate            numeric(4,2) NOT NULL DEFAULT 7.5 CHECK (pension_rate BETWEEN 0 AND 20),
    is_bank_verified        boolean NOT NULL DEFAULT false,
    is_tin_verified         boolean NOT NULL DEFAULT false
);

CREATE TABLE public.teacher_background_logs (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id  uuid NOT NULL REFERENCES public.teachers(id),
    campus_id   uuid NOT NULL REFERENCES public.campus(id),
    event_type  text NOT NULL CHECK (event_type IN ('appointment','disciplinary','promotion','transfer','exit','police_clearance','qualification')),
    description text NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    recorded_by uuid NOT NULL REFERENCES public.app_users(id)
);

CREATE TABLE public.teacher_exit_records (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id      uuid NOT NULL REFERENCES public.teachers(id),
    campus_id       uuid NOT NULL REFERENCES public.campus(id),
    exit_date       date NOT NULL,
    reason          text NOT NULL,
    clearance_doc   bytea,
    last_pay_period citext,
    signed_by       uuid NOT NULL REFERENCES public.managers(id)
);

CREATE TABLE public.payroll_entries (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id        uuid NOT NULL REFERENCES public.teachers(id),
    campus_id         uuid NOT NULL REFERENCES public.campus(id),
    pay_period        citext NOT NULL,            -- 2026-08
    hours             numeric(6,1) NOT NULL DEFAULT 0,
    base_pay          numeric(14,2) NOT NULL DEFAULT 0,
    hardship_allowance numeric(14,2) NOT NULL DEFAULT 0,
    gross             numeric(14,2) NOT NULL DEFAULT 0,
    pension_deduction numeric(14,2) NOT NULL DEFAULT 0,
    net               numeric(14,2) NOT NULL DEFAULT 0,
    submitted_by      uuid NOT NULL REFERENCES public.app_users(id),
    status            payout_state NOT NULL DEFAULT 'pending',
    created_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (teacher_id, pay_period)
);

-- ---------------------------------------------------------------------------
-- 7. CRYPTOGRAPHIC RECORD LOCKING (Phase 2)
-- ---------------------------------------------------------------------------
CREATE TABLE public.record_locks (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_id              uuid NOT NULL REFERENCES public.campus(id),
    entity_type            lock_entity NOT NULL,
    entity_id              uuid NOT NULL,
    payload_hash           text NOT NULL,             -- SHA-256 canonical digest
    canonical_payload      jsonb NOT NULL,            -- frozen canonical snapshot
    signature              bytea NOT NULL,            -- Ed25519 signature by dean
    signature_scheme       signature_scheme NOT NULL DEFAULT 'ed25519',
    key_version            int NOT NULL DEFAULT 1,
    locked_by              uuid NOT NULL REFERENCES public.managers(id),
    locked_at              timestamptz NOT NULL DEFAULT now(),
    unlocked_by            uuid REFERENCES public.managers(id),
    unlocked_at            timestamptz,
    unlock_signature       bytea,                     -- state-admin / system counter-signature
    superseded_by          uuid REFERENCES public.record_locks(id),
    UNIQUE (entity_type, entity_id)
);

-- Freeze a row: once locked, ordinary UPDATE/DELETE raises.
CREATE OR REPLACE FUNCTION app.enforce_record_lock() RETURNS trigger AS $$
DECLARE
  lock_row record;
  row_id uuid;
BEGIN
  IF TG_OP = 'DELETE' THEN
    row_id := OLD.id;
  ELSE
    row_id := NEW.id;
  END IF;

  SELECT * INTO lock_row
    FROM public.record_locks
   WHERE entity_type = TG_ARGV[0]::public.lock_entity
     AND entity_id = row_id
     AND unlocked_at IS NULL;

  IF lock_row.id IS NOT NULL AND TG_OP <> 'INSERT' THEN
    RAISE EXCEPTION 'neemis.record_locked: % is frozen by manager %, payload_hash %',
      TG_ARGV[0], lock_row.locked_by, lock_row.payload_hash
      USING ERRCODE = '55000',
            DETAIL = format('locked_at=%s payload_hash=%s', lock_row.locked_at, lock_row.payload_hash);
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach freeze triggers to the lockable Phase-1/2 entities.
CREATE TRIGGER trg_attendance_freeze BEFORE UPDATE OR DELETE ON public.attendance
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('attendance');
CREATE TRIGGER trg_exam_freeze BEFORE UPDATE OR DELETE ON public.exam_sheets
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('exam_sheet');
CREATE TRIGGER trg_payroll_freeze BEFORE UPDATE OR DELETE ON public.payroll_entries
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('payroll_entry');
CREATE TRIGGER trg_teacher_freeze BEFORE UPDATE OR DELETE ON public.teachers
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('teacher_profile');
CREATE TRIGGER trg_classroom_freeze BEFORE UPDATE OR DELETE ON public.classrooms
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('classroom');
CREATE TRIGGER trg_section_freeze BEFORE UPDATE OR DELETE ON public.course_sections
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('course_section');
CREATE TRIGGER trg_student_freeze BEFORE UPDATE OR DELETE ON public.students
  FOR EACH ROW EXECUTE FUNCTION app.enforce_record_lock('student_record');

-- Auxiliary locking summary table used by dean review screens.
CREATE TABLE public.pending_locks (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_id      uuid NOT NULL REFERENCES public.campus(id),
    entity_type    lock_entity NOT NULL,
    entity_id      uuid NOT NULL,
    payload_hash   text,
    locked_at      timestamptz,
    summary_json   jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (entity_type, entity_id)
);

-- ---------------------------------------------------------------------------
-- 8. FOUR-PHASE PIPELINE ARTIFACTS
-- ---------------------------------------------------------------------------
CREATE TABLE public.ingestion_jobs (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    phase       smallint NOT NULL CHECK (phase IN (1,2,3,4)),
    campus_id   uuid REFERENCES public.campus(id),
    source      data_source NOT NULL,
    payload     jsonb NOT NULL,
    validation_errors jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz
);

CREATE TABLE public.aggregation_batches (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    batch_date   date NOT NULL,
    phase        smallint NOT NULL CHECK (phase IN (3,4)),
    batch_state  batch_state NOT NULL DEFAULT 'queued',
    started_at   timestamptz,
    finished_at  timestamptz,
    stats        jsonb NOT NULL DEFAULT '{}'::jsonb,
    error        text
);

-- Central state registries (Phase 3 read models). These are deliberately
-- NOT campus-scoped; only state admins/systems query them.
CREATE TABLE central.student_registry (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id        uuid UNIQUE NOT NULL REFERENCES public.students(id),
    ne_sid            text UNIQUE NOT NULL,
    current_campus_id uuid NOT NULL REFERENCES public.campus(id),
    schooling_history jsonb NOT NULL DEFAULT '[]'::jsonb,   -- chronological mobility tree
    latest_enrollment jsonb,
    gpa_trend         jsonb NOT NULL DEFAULT '[]'::jsonb,
    aggregated_at     timestamptz NOT NULL DEFAULT now(),
    snapshot_key      text NOT NULL UNIQUE                  -- idempotency key for batch
);

CREATE TABLE central.teacher_registry (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id         uuid UNIQUE NOT NULL REFERENCES public.teachers(id),
    ne_tid             text UNIQUE NOT NULL,
    current_campus_id  uuid NOT NULL REFERENCES public.campus(id),
    qualifications     jsonb NOT NULL DEFAULT '[]'::jsonb,
    certifications     jsonb NOT NULL DEFAULT '[]'::jsonb,
    payroll_profile    jsonb,
    status             employment_state NOT NULL,
    aggregated_at      timestamptz NOT NULL DEFAULT now(),
    snapshot_key       text NOT NULL UNIQUE
);

CREATE TABLE central.funding_payouts (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    campus_id     uuid NOT NULL REFERENCES public.campus(id),
    period        citext NOT NULL,
    funding_kind  funding_kind NOT NULL,
    formula       jsonb NOT NULL,
    amount        numeric(16,2) NOT NULL CHECK (amount >= 0),
    status        payout_state NOT NULL DEFAULT 'pending',
    approved_by   uuid REFERENCES public.managers(id),
    approved_at   timestamptz,
    paid_at       timestamptz,
    ledger_ref    text,
    UNIQUE (campus_id, period, funding_kind)
);

CREATE TABLE central.kpi_rollups (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    state_code     char(2) NOT NULL,
    campus_id      uuid REFERENCES public.campus(id),
    period_start   date NOT NULL,
    period_end     date NOT NULL,
    metrics        jsonb NOT NULL DEFAULT '{}'::jsonb,
    computed_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (campus_id, period_start, period_end)
);

-- ---------------------------------------------------------------------------
-- 9. ROW-LEVEL SECURITY POLICIES
-- ---------------------------------------------------------------------------
-- Tenant tables: clerk/dean only see rows for their session campus.
-- state_admin / system / aggregator bypass on state-owned functions only.

ALTER TABLE public.campus ENABLE ROW LEVEL SECURITY;
-- Campus metadata is reference-like: authenticated roles may read it, but only
-- state/system roles may write it.
CREATE POLICY p_campus_read ON public.campus
  USING (app.current_role() <> 'anonymous' OR app.is_state_role())
  WITH CHECK (app.is_state_role());

ALTER TABLE public.managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_mobility ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfer_clearances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.majors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classrooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_sheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.truancy_marks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_qualifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_payroll_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_background_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_exit_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.record_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_jobs ENABLE ROW LEVEL SECURITY;

-- Managers / users are domain-scoped by campus; state role can read all.
DO $$
DECLARE tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'students','enrollments','student_mobility','transfer_clearances',
    'majors','classrooms','course_sections','course_enrollments',
    'transcripts','exam_sheets','attendance','incident_reports',
    'truancy_marks','teachers','teacher_qualifications','teacher_certifications',
    'teacher_assignments','teacher_payroll_profiles','teacher_background_logs',
    'teacher_exit_records','payroll_entries','record_locks','pending_locks',
    'ingestion_jobs','managers'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY p_%1$s_tenant ON public.%1$s
         USING (campus_id = app.current_campus_id() OR app.is_state_role())
         WITH CHECK (campus_id = app.current_campus_id() OR app.is_state_role());', tbl);
  END LOOP;
END $$;

ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_app_users_tenant ON public.app_users
  USING (campus_id = app.current_campus_id()
         OR app.is_state_role()
         OR id = NULLIF(current_setting('neemis.user_id', true), '')::uuid)
  WITH CHECK (campus_id = app.current_campus_id()
              OR app.is_state_role()
              OR id = NULLIF(current_setting('neemis.user_id', true), '')::uuid);

-- Central tables are state-owned (no RLS for full state access).
ALTER TABLE central.student_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_central_state ON central.student_registry
  USING (app.is_state_role()) WITH CHECK (app.is_state_role());
ALTER TABLE central.teacher_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_central_state ON central.teacher_registry
  USING (app.is_state_role()) WITH CHECK (app.is_state_role());
ALTER TABLE central.funding_payouts ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_central_state ON central.funding_payouts
  USING (app.is_state_role()) WITH CHECK (app.is_state_role());
ALTER TABLE central.kpi_rollups ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_central_state ON central.kpi_rollups
  USING (app.is_state_role()) WITH CHECK (app.is_state_role());

COMMIT;
